error missing drawables
Android resource linking failed
com.cashpal.app-mergeDebugResources-69:/layout/fragment_receipt.xml:33: error: resource drawable/ic_arrow_back (aka com.cashpal.app:drawable/ic_arrow_back) not found.
com.cashpal.app-mergeDebugResources-69:/layout/fragment_receipt.xml:91: error: resource drawable/mtrl_ic_done_all (aka com.cashpal.app:drawable/mtrl_ic_done_all) not found.
com.cashpal.app-mergeDebugResources-69:/layout/fragment_receipt.xml:182: error: resource drawable/ic_menu (aka com.cashpal.app:drawable/ic_menu) not found.
com.cashpal.app-mergeDebugResources-69:/layout/fragment_receipt.xml:330: error: resource drawable/mtrl_ic_copy (aka com.cashpal.app:drawable/mtrl_ic_copy) not found.
com.cashpal.app-mergeDebugResources-69:/layout/fragment_receipt.xml:520: error: resource drawable/mtrl_ic_share (aka com.cashpal.app:drawable/mtrl_ic_share) not found.
com.cashpal.app-mergeDebugResources-69:/layout/fragment_receipt.xml:550: error: resource drawable/mtrl_ic_download (aka com.cashpal.app:drawable/mtrl_ic_download) not found.
com.cashpal.app-mergeDebugResources-69:/layout/fragment_receipt.xml:599: error: resource color/muted (aka com.cashpal.app:color/muted) not found.
error: failed linking file resources.